version: '3'

services:
  rust:
    image: djf/rusty-golf
    container_name: rusty-golf
    ports:
      - 9000:8081
    environment:
      - DB_HOST=10.8.0.201
      - DB_PORT=5432
      - DB_USER=golfuser
      - DB_PASSWORD=/secrets/db_password
      - DB_NAME=golf
    volumes:
      - rusty_golf_data:/data
      - ../tests/test5_dbprefill.json:/eup.json:z
      - ./init_db.sql:/db_startup_script.sql:z
    entrypoint: ["/usr/bin/tini", "--", "/usr/local/cargo/bin/rusty-golf"]
    command: [
      "--db-type=sqlite"
      , "--db-name=/data/xxx"
      , "--db-startup-script=/init_db.sql"
      , "--db-populate-json=/eup.json"
      , "--dont-poll-espn-after-num-days=0",
      ]
    networks:
      rusty-golf:
        ipv4_address: 10.8.0.202

volumes:
  rusty_golf_data:
    external: true

networks:
  rusty-golf:
    external: true